# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tokengenerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokengenerator',
            name='tokens',
            field=models.CharField(default='LTqk', max_length=255),
        ),
    ]
