# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import space.apps.backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180125_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokengenerator',
            name='tokens',
            field=models.CharField(default=space.apps.backend.models.maketokem, max_length=255),
        ),
    ]
