# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180125_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokengenerator',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
