# Generated by Django 2.0.1 on 2018-01-25 14:02

from django.db import migrations, models
import space.apps.backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_tokengenerator_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokengenerator',
            name='tokens',
            field=models.CharField(default=space.apps.backend.models.maketokem, max_length=255, unique=True),
        ),
    ]
